[logging]
level = "info"
target = "stdout"
color = "auto"
file_name = "./pim-mcp.log"
file_size_limit = 0
syslog_network = "tcp"
syslog_address = "localhost:601"
syslog_encoding = "rfc5424"
syslog_facility = 4

[server]
address = "localhost:0"
protocol = "http"
cert_file = ""
key_file = ""
public_url = ""
trusted_proxies = [ ]
trusted_headers = [ ]
allowed_origins = [ ]
access_log = ""
access_log_size_limit = 0

[provider.msgraph]
client_id = ""
client_secret = ""
tenant_id = ""