// Package rest Code generated by swaggo/swag. DO NOT EDIT
package rest

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "url": "https://github.com/tdrn-org/pim-mcp"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/v1/login": {
            "post": {
                "description": "Initiate PIM provider login for the current user. Optionally provide an api_key for session recovery.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "Initiate PIM provider login",
                "parameters": [
                    {
                        "description": "optional api_key for session recovery",
                        "name": "body",
                        "in": "body",
                        "schema": {
                            "$ref": "#/definitions/rest.loginRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/rest.SessionInfo"
                        }
                    },
                    "302": {
                        "description": "Found",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "401": {
                        "description": "invalid api_key",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "server error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/v1/ping": {
            "get": {
                "description": "Ping the server to check general health",
                "produces": [
                    "text/plain"
                ],
                "summary": "Ping the server",
                "responses": {
                    "200": {
                        "description": "ok",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "server error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/v1/session": {
            "get": {
                "description": "Get the session for the current user",
                "produces": [
                    "application/json"
                ],
                "summary": "Get the user session",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/rest.SessionInfo"
                        }
                    },
                    "500": {
                        "description": "server error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "delete": {
                "description": "Delete the session for the current user",
                "produces": [
                    "application/json"
                ],
                "summary": "Delete the user session",
                "responses": {
                    "200": {
                        "description": "ok",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "server error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "rest.CredentialInfo": {
            "type": "object",
            "properties": {
                "valid": {
                    "type": "boolean"
                }
            }
        },
        "rest.SessionInfo": {
            "type": "object",
            "properties": {
                "api_key": {
                    "type": "string"
                },
                "credentials": {
                    "$ref": "#/definitions/rest.CredentialInfo"
                },
                "provider_name": {
                    "type": "string"
                }
            }
        },
        "rest.loginRequest": {
            "type": "object",
            "properties": {
                "api_key": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:9123",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "PIM MCP Server REST API",
	Description:      "MCP server providing Agent access to PIM services.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
